# Generated by Django 5.1.2 on 2024-10-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('max_participants', models.IntegerField()),
                ('participants', models.ManyToManyField(related_name='events', to='members.member')),
            ],
        ),
    ]
