# Generated by Django 5.1.2 on 2024-10-28 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_featured'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility'),
        ),
    ]
